name: brianceci
favicon: null
layout_spectrum: 0.04521348117850721
typography_spectrum: 0.3134119240567088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7757113222032785
  lightness: 0.6555746176745743
  saturation: 0.32546161371283233
  rhythmicContrast: 0.21673732134513557
purpose: []
