name: brianceci
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65417
title: The Personal Portfolio of Brian Ceci
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-24267216-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#787676'
    - '#c9c8c8'
    - '#5a5757'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
